// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package nodejs

import (
	"bytes"
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/googleapis/librarian/internal/config"
)

var (
	autogeneratedMarker = []byte("This file is automatically generated by gapic-generator-typescript.")
	// Files to delete without any checking, relative to the package directory.
	simpleFilesToClean = []string{
		"protos/protos.d.ts",
		"protos/protos.js",
		"protos/protos.json",
		"samples/package.json",
		"package.json",
		"tsconfig.json",
		"webpack.config.js",
		".eslintignore",
		".gitignore",
		".nycrc",
		"README.md",
	}
	sourceDirectoriesToClean = []string{
		"samples",
		"src",
		"system-test",
		"test",
	}
)

// Clean removes all generated code from beneath the given library's
// output directory. If the output directory does not currently exist, this
// function is a no-op.
func Clean(lib *config.Library) error {
	_, err := os.Stat(lib.Output)
	if errors.Is(err, fs.ErrNotExist) {
		return nil
	}
	keepSet := make(map[string]bool)
	for _, k := range lib.Keep {
		keepSet[k] = true
	}
	if err := cleanFiles(lib, keepSet, "protos", ".proto", nil); err != nil {
		return err
	}
	if err := cleanFiles(lib, keepSet, "src", ".json", nil); err != nil {
		return err
	}
	for _, sourceDirectory := range sourceDirectoriesToClean {
		if err := cleanFiles(lib, keepSet, sourceDirectory, ".js", autogeneratedMarker); err != nil {
			return err
		}
		if err := cleanFiles(lib, keepSet, sourceDirectory, ".ts", autogeneratedMarker); err != nil {
			return err
		}
	}
	for _, file := range simpleFilesToClean {
		if keepSet[file] {
			continue
		}
		if err := os.Remove(filepath.Join(lib.Output, file)); err != nil && !errors.Is(err, fs.ErrNotExist) {
			return err
		}
	}
	return nil
}

// cleanFiles recursively deletes files with a given suffix from a subdirectory
// of the given library's output directory, obeying the keep list (passed as
// keepSet for efficiency). If marker is non-empty, only files with content
// containing it are deleted; this is used to ensure we only delete generated
// source code, preserving handwritten code.
func cleanFiles(lib *config.Library, keepSet map[string]bool, subDir, suffix string, marker []byte) error {
	dir := filepath.Join(lib.Output, subDir)
	// If the directory we'd clean doesn't exist, that's fine.
	_, err := os.Stat(dir)
	if errors.Is(err, fs.ErrNotExist) {
		return nil
	}
	return filepath.WalkDir(dir, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() || !strings.HasSuffix(d.Name(), suffix) {
			return nil
		}
		if len(marker) != 0 {
			content, err := os.ReadFile(path)
			if err != nil {
				return err
			}
			if !bytes.Contains(content, marker) {
				return nil
			}
		}
		relPath, err := filepath.Rel(lib.Output, path)
		if err != nil {
			return err
		}
		if keepSet[relPath] {
			return nil
		}
		return os.Remove(path)
	})
}
