// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package nodejs

import (
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"testing"

	"github.com/googleapis/librarian/internal/config"
)

func TestClean(t *testing.T) {
	t.Parallel()
	for _, test := range []struct {
		name        string
		keep        []string
		setupFiles  []string
		contentMap  map[string]string
		wantDeleted []string
		wantKeep    []string
	}{
		{
			name: "protos are deleted only from protos",
			setupFiles: []string{
				"protos/a.proto",
				"protos/kept.proto",
				"protos/subdir/a.proto",
				"other/a.proto",
			},
			keep: []string{"protos/kept.proto"},
			wantDeleted: []string{
				"protos/a.proto",
				"protos/subdir/a.proto",
			},
			wantKeep: []string{
				"protos/kept.proto",
				"other/a.proto",
			},
		},
		{
			name: "json files are deleted only from src",
			setupFiles: []string{
				"src/x.json",
				"src/subdir/x.json",
				"src/subdir/kept.json",
				"protos/x.json",
				"root.json",
			},
			keep: []string{"src/subdir/kept.json"},
			wantDeleted: []string{
				"src/x.json",
				"src/subdir/x.json",
			},
			wantKeep: []string{
				"src/subdir/kept.json",
				"protos/x.json",
				"root.json",
			},
		},
		{
			name: "js and ts files are only deleted if they have markers",
			setupFiles: []string{
				"src/x.js",
				"src/handwritten.js",
				"src/x.ts",
			},
			contentMap: map[string]string{
				"src/x.js":           "comments\n" + string(autogeneratedMarker) + "\ncode",
				"src/handwritten.js": "code",
				"src/x.ts":           "comments\n" + string(autogeneratedMarker) + "\ncode",
			},
			wantDeleted: []string{
				"src/x.js",
				"src/x.ts",
			},
			wantKeep: []string{
				"src/handwritten.js",
			},
		},
		{
			name: "simple files obey keep",
			setupFiles: []string{
				"protos/protos.js",
				"protos/protos.json",
				"samples/package.json",
				"other.json",
			},
			keep: []string{"protos/protos.json"},
			wantDeleted: []string{
				"protos/protos.js",
				"samples/package.json",
			},
			wantKeep: []string{
				"protos/protos.json",
			},
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			repoRoot := t.TempDir()
			lib := &config.Library{
				Name:   "test",
				Output: filepath.Join(repoRoot, "packages", "test"),
				Keep:   test.keep,
			}
			for _, file := range test.setupFiles {
				path := filepath.Join(lib.Output, file)
				if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
					t.Fatal(err)
				}
				content := ""
				if c, ok := test.contentMap[file]; ok {
					content = c
				}
				if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
					t.Fatal(err)
				}
			}
			if err := Clean(lib); err != nil {
				t.Fatal(err)
			}
			for _, file := range test.wantDeleted {
				fullPath := filepath.Join(lib.Output, file)
				if _, err := os.Stat(fullPath); !errors.Is(err, fs.ErrNotExist) {
					t.Errorf("file %s was not deleted: %v", file, err)
				}
			}
			for _, file := range test.wantKeep {
				fullPath := filepath.Join(lib.Output, file)
				if _, err := os.Stat(fullPath); err != nil {
					t.Errorf("file %s was not kept: %v", file, err)
				}
			}
		})
	}
}

func TestClean_NonExistentOutput(t *testing.T) {
	t.Parallel()
	lib := &config.Library{
		Output: filepath.Join(t.TempDir(), "nonexistent"),
	}
	if err := Clean(lib); err != nil {
		t.Fatal(err)
	}
}

func TestClean_Error(t *testing.T) {
	for _, test := range []struct {
		name    string
		setup   func(t *testing.T, outputDir string)
		wantErr error
	}{
		{
			name: "unreadable directory during walk",
			setup: func(t *testing.T, outputDir string) {
				unreadableDir := filepath.Join(outputDir, "protos", "unreadable")
				if err := os.MkdirAll(unreadableDir, 0o755); err != nil {
					t.Fatal(err)
				}
				if err := os.Chmod(unreadableDir, 0o000); err != nil {
					t.Fatal(err)
				}
				t.Cleanup(func() {
					_ = os.Chmod(unreadableDir, 0o755)
				})
			},
			wantErr: os.ErrPermission,
		},
		{
			name: "unreadable source file when checking autogenerated marker",
			setup: func(t *testing.T, outputDir string) {
				filePath := filepath.Join(outputDir, "src", "unreadable.js")
				if err := os.MkdirAll(filepath.Dir(filePath), 0o755); err != nil {
					t.Fatal(err)
				}
				if err := os.WriteFile(filePath, []byte("content"), 0o644); err != nil {
					t.Fatal(err)
				}
				if err := os.Chmod(filePath, 0o000); err != nil {
					t.Fatal(err)
				}
				t.Cleanup(func() {
					_ = os.Chmod(filePath, 0o644)
				})
			},
			wantErr: os.ErrPermission,
		},
		{
			name: "cannot remove file in read-only directory",
			setup: func(t *testing.T, outputDir string) {
				protosDir := filepath.Join(outputDir, "protos")
				if err := os.MkdirAll(protosDir, 0o755); err != nil {
					t.Fatal(err)
				}
				protoFile := filepath.Join(protosDir, "a.proto")
				if err := os.WriteFile(protoFile, []byte("content"), 0o644); err != nil {
					t.Fatal(err)
				}
				if err := os.Chmod(protosDir, 0o555); err != nil {
					t.Fatal(err)
				}
				t.Cleanup(func() {
					_ = os.Chmod(protosDir, 0o755)
				})
			},
			wantErr: os.ErrPermission,
		},
		{
			name: "cannot remove simple file in read-only directory",
			setup: func(t *testing.T, outputDir string) {
				pkgJSON := filepath.Join(outputDir, "package.json")
				if err := os.WriteFile(pkgJSON, []byte("{}"), 0o644); err != nil {
					t.Fatal(err)
				}
				if err := os.Chmod(outputDir, 0o555); err != nil {
					t.Fatal(err)
				}
				t.Cleanup(func() {
					_ = os.Chmod(outputDir, 0o755)
				})
			},
			wantErr: os.ErrPermission,
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			outputDir := t.TempDir()
			test.setup(t, outputDir)
			lib := &config.Library{
				Name:   "test",
				Output: outputDir,
			}
			err := Clean(lib)
			if !errors.Is(err, test.wantErr) {
				t.Errorf("Clean() error = %v, wantErr = %v", err, test.wantErr)
			}
		})
	}
}
