// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package writer formats and prints Java AST structures into Java source code.
package writer

import (
	"fmt"
	"sort"
	"strings"

	"github.com/googleapis/librarian/internal/gapic/java/engine/ast"
	"github.com/googleapis/librarian/internal/gapic/java/engine/lexicon"
)

// WriteClass renders a ClassDefinition to a complete Java source file string.
func WriteClass(c *ast.ClassDefinition) string {
	var sb strings.Builder

	// Header License comment
	sb.WriteString("// Generated by gapic-generator-java. DO NOT EDIT!\n\n")

	// Package
	if c.PackageName != "" {
		fmt.Fprintf(&sb, "package %s;\n\n", c.PackageName)
	}

	// Imports
	imports := collectImports(c)
	if len(imports) > 0 {
		for _, imp := range imports {
			fmt.Fprintf(&sb, "import %s;\n", imp)
		}
		sb.WriteString("\n")
	}

	// Class body
	writeClassDefinition(&sb, c, 0)
	return sb.String()
}

func collectImports(c *ast.ClassDefinition) []string {
	impSet := make(map[string]bool)
	for _, imp := range c.Imports {
		if imp != "" && !strings.HasPrefix(imp, "java.lang.") && !isSamePackage(imp, c.PackageName) {
			impSet[imp] = true
		}
	}
	// Walk AST to gather any referenced types
	gatherTypeImports(c.ExtendsType, c.PackageName, impSet)
	for _, imp := range c.ImplementsTypes {
		gatherTypeImports(imp, c.PackageName, impSet)
	}
	for _, f := range c.Fields {
		if f != nil && f.Variable != nil {
			gatherTypeImports(f.Variable.Type, c.PackageName, impSet)
		}
	}
	for _, m := range c.Methods {
		gatherMethodImports(m, c.PackageName, impSet)
	}
	for _, inner := range c.InnerClasses {
		innerImps := collectImports(inner)
		for _, imp := range innerImps {
			if !isSamePackage(imp, c.PackageName) {
				impSet[imp] = true
			}
		}
	}

	res := make([]string, 0, len(impSet))
	for imp := range impSet {
		res = append(res, imp)
	}
	sort.Strings(res)
	return res
}

func isSamePackage(fullType, pkg string) bool {
	if pkg == "" {
		return false
	}
	lastDot := strings.LastIndex(fullType, ".")
	if lastDot == -1 {
		return true
	}
	return fullType[:lastDot] == pkg
}

func gatherTypeImports(t *ast.TypeNode, currentPkg string, impSet map[string]bool) {
	if t == nil || t.Kind != ast.KindObject || t.Package == "" || t.Package == "java.lang" {
		return
	}
	if t.Package != currentPkg {
		impSet[t.Package+"."+t.Name] = true
	}
	for _, g := range t.Generics {
		gatherTypeImports(g, currentPkg, impSet)
	}
	if t.ExtendsBound != nil {
		gatherTypeImports(t.ExtendsBound, currentPkg, impSet)
	}
	if t.SuperBound != nil {
		gatherTypeImports(t.SuperBound, currentPkg, impSet)
	}
}

func gatherMethodImports(m *ast.MethodDefinition, currentPkg string, impSet map[string]bool) {
	if m == nil {
		return
	}
	gatherTypeImports(m.ReturnType, currentPkg, impSet)
	for _, arg := range m.Arguments {
		if arg != nil && arg.Variable != nil {
			gatherTypeImports(arg.Variable.Type, currentPkg, impSet)
		}
	}
	for _, ex := range m.ThrowsExceptions {
		gatherTypeImports(ex, currentPkg, impSet)
	}
}

func indent(level int) string {
	return strings.Repeat("  ", level)
}

func writeJavaDoc(sb *strings.Builder, doc *ast.JavaDocComment, level int) {
	if doc == nil || (len(doc.Paragraphs) == 0 && len(doc.Params) == 0 && doc.Returns == "" && len(doc.Throws) == 0 && doc.Deprecated == "") {
		return
	}
	ind := indent(level)
	sb.WriteString(ind + "/**\n")
	for i, p := range doc.Paragraphs {
		if i > 0 {
			sb.WriteString(ind + " *\n")
			sb.WriteString(ind + " * <p> " + p + "\n")
		} else {
			sb.WriteString(ind + " * " + p + "\n")
		}
	}
	if len(doc.Params) > 0 {
		sb.WriteString(ind + " *\n")
		for _, param := range doc.Params {
			fmt.Fprintf(sb, "%s * @param %s %s\n", ind, param.Name, param.Description)
		}
	}
	if doc.Returns != "" {
		fmt.Fprintf(sb, "%s * @return %s\n", ind, doc.Returns)
	}
	if len(doc.Throws) > 0 {
		for _, th := range doc.Throws {
			fmt.Fprintf(sb, "%s * @throws %s %s\n", ind, th.Exception, th.Description)
		}
	}
	if doc.Deprecated != "" {
		fmt.Fprintf(sb, "%s * @deprecated %s\n", ind, doc.Deprecated)
	}
	sb.WriteString(ind + " */\n")
}

func writeAnnotation(sb *strings.Builder, ann *ast.AnnotationNode, level int) {
	if ann == nil || ann.Type == nil {
		return
	}
	ind := indent(level)
	sb.WriteString(ind + "@" + ann.Type.Name)
	if ann.Value != nil {
		sb.WriteString("(" + writeExpr(ann.Value) + ")")
	} else if len(ann.Attributes) > 0 {
		sb.WriteString("(")
		first := true
		for k, v := range ann.Attributes {
			if !first {
				sb.WriteString(", ")
			}
			fmt.Fprintf(sb, "%s = %s", k, writeExpr(v))
			first = false
		}
		sb.WriteString(")")
	}
	sb.WriteString("\n")
}

func writeClassDefinition(sb *strings.Builder, c *ast.ClassDefinition, level int) {
	ind := indent(level)

	// JavaDoc
	writeJavaDoc(sb, c.JavaDoc, level)

	// Annotations
	for _, ann := range c.Annotations {
		writeAnnotation(sb, ann, level)
	}

	// Class Header
	sb.WriteString(ind)
	if c.Scope != "" {
		sb.WriteString(string(c.Scope) + " ")
	}
	for _, m := range c.Modifiers {
		sb.WriteString(string(m) + " ")
	}
	if c.IsInterface {
		sb.WriteString("interface ")
	} else if c.IsEnum {
		sb.WriteString("enum ")
	} else {
		sb.WriteString("class ")
	}
	sb.WriteString(c.Name)

	if c.ExtendsType != nil {
		sb.WriteString(" extends " + c.ExtendsType.String())
	}
	if len(c.ImplementsTypes) > 0 {
		sb.WriteString(" implements ")
		for i, imp := range c.ImplementsTypes {
			if i > 0 {
				sb.WriteString(", ")
			}
			sb.WriteString(imp.String())
		}
	}
	sb.WriteString(" {\n")

	// Enum values
	if c.IsEnum && len(c.EnumValues) > 0 {
		for i, ev := range c.EnumValues {
			sb.WriteString(indent(level+1) + ev.Name)
			if len(ev.Arguments) > 0 {
				sb.WriteString("(")
				for j, arg := range ev.Arguments {
					if j > 0 {
						sb.WriteString(", ")
					}
					sb.WriteString(writeExpr(arg))
				}
				sb.WriteString(")")
			}
			if i < len(c.EnumValues)-1 {
				sb.WriteString(",\n")
			} else {
				sb.WriteString(";\n\n")
			}
		}
	}

	// Fields
	for _, f := range c.Fields {
		writeField(sb, f, level+1)
	}
	if len(c.Fields) > 0 && (len(c.Methods) > 0 || len(c.InnerClasses) > 0) {
		sb.WriteString("\n")
	}

	// Methods
	for i, m := range c.Methods {
		if i > 0 {
			sb.WriteString("\n")
		}
		writeMethod(sb, m, level+1)
	}

	// Inner Classes
	for _, inner := range c.InnerClasses {
		sb.WriteString("\n")
		writeClassDefinition(sb, inner, level+1)
	}

	sb.WriteString(ind + "}\n")
}

func writeField(sb *strings.Builder, f *ast.VariableExpr, level int) {
	if f == nil || f.Variable == nil {
		return
	}
	ind := indent(level)
	sb.WriteString(ind)
	if f.Scope != "" {
		sb.WriteString(string(f.Scope) + " ")
	}
	if f.IsStatic {
		sb.WriteString("static ")
	}
	if f.IsFinal {
		sb.WriteString("final ")
	}
	if f.Variable.Type != nil {
		sb.WriteString(f.Variable.Type.String() + " ")
	}
	sb.WriteString(f.Variable.Name)
	if f.InitExpr != nil {
		sb.WriteString(" = " + writeExpr(f.InitExpr))
	}
	sb.WriteString(";\n")
}

func writeMethod(sb *strings.Builder, m *ast.MethodDefinition, level int) {
	if m == nil {
		return
	}
	ind := indent(level)

	// JavaDoc
	writeJavaDoc(sb, m.JavaDoc, level)

	// Annotations
	if m.IsOverride {
		sb.WriteString(ind + "@Override\n")
	}
	for _, ann := range m.Annotations {
		writeAnnotation(sb, ann, level)
	}

	// Method signature
	sb.WriteString(ind)
	if m.Scope != "" {
		sb.WriteString(string(m.Scope) + " ")
	}
	for _, mod := range m.Modifiers {
		sb.WriteString(string(mod) + " ")
	}
	if m.IsAbstract {
		sb.WriteString("abstract ")
	}
	if len(m.TemplateGenerics) > 0 {
		sb.WriteString("<")
		for i, g := range m.TemplateGenerics {
			if i > 0 {
				sb.WriteString(", ")
			}
			sb.WriteString(g.String())
		}
		sb.WriteString("> ")
	}
	if !m.IsConstructor {
		if m.ReturnType != nil {
			sb.WriteString(m.ReturnType.String() + " ")
		} else {
			sb.WriteString("void ")
		}
	}
	sb.WriteString(m.Name + "(")

	for i, arg := range m.Arguments {
		if i > 0 {
			sb.WriteString(", ")
		}
		if arg.IsFinal {
			sb.WriteString("final ")
		}
		if arg.Variable != nil {
			if arg.Variable.Type != nil {
				sb.WriteString(arg.Variable.Type.String() + " ")
			}
			sb.WriteString(arg.Variable.Name)
		}
	}
	sb.WriteString(")")

	if len(m.ThrowsExceptions) > 0 {
		sb.WriteString(" throws ")
		for i, th := range m.ThrowsExceptions {
			if i > 0 {
				sb.WriteString(", ")
			}
			sb.WriteString(th.Name)
		}
	}

	if m.IsAbstract {
		sb.WriteString(";\n")
		return
	}

	sb.WriteString(" {\n")
	for _, stmt := range m.Statements {
		writeStatement(sb, stmt, level+1)
	}
	sb.WriteString(ind + "}\n")
}

func writeStatement(sb *strings.Builder, stmt ast.Statement, level int) {
	if stmt == nil {
		return
	}
	ind := indent(level)
	switch s := stmt.(type) {
	case *ast.LineComment:
		sb.WriteString(ind + "// " + s.Comment + "\n")
	case *ast.BlockComment:
		sb.WriteString(ind + "/* " + s.Comment + " */\n")
	case *ast.ExprStatement:
		sb.WriteString(ind + writeExpr(s.Expr) + ";\n")
	case *ast.VariableExpr:
		sb.WriteString(ind)
		if s.IsFinal {
			sb.WriteString("final ")
		}
		if s.Variable != nil && s.Variable.Type != nil {
			sb.WriteString(s.Variable.Type.String() + " ")
		}
		if s.Variable != nil {
			sb.WriteString(s.Variable.Name)
		}
		if s.InitExpr != nil {
			sb.WriteString(" = " + writeExpr(s.InitExpr))
		}
		sb.WriteString(";\n")
	case *ast.AssignmentExpr:
		sb.WriteString(ind + writeExpr(s) + ";\n")
	case *ast.AssignmentOperationExpr:
		sb.WriteString(ind + writeExpr(s) + ";\n")
	case *ast.ReturnExpr:
		sb.WriteString(ind + "return")
		if s.Expr != nil {
			sb.WriteString(" " + writeExpr(s.Expr))
		}
		sb.WriteString(";\n")
	case *ast.ThrowExpr:
		sb.WriteString(ind + "throw " + writeExpr(s.Expr) + ";\n")
	case *ast.IfStatement:
		sb.WriteString(ind + "if (" + writeExpr(s.Condition) + ") {\n")
		for _, thenStmt := range s.ThenStatements {
			writeStatement(sb, thenStmt, level+1)
		}
		for _, elseIf := range s.ElseIfs {
			sb.WriteString(ind + "} else if (" + writeExpr(elseIf.Condition) + ") {\n")
			for _, elseIfStmt := range elseIf.Statements {
				writeStatement(sb, elseIfStmt, level+1)
			}
		}
		if len(s.ElseStatements) > 0 {
			sb.WriteString(ind + "} else {\n")
			for _, elseStmt := range s.ElseStatements {
				writeStatement(sb, elseStmt, level+1)
			}
		}
		sb.WriteString(ind + "}\n")
	case *ast.WhileStatement:
		sb.WriteString(ind + "while (" + writeExpr(s.Condition) + ") {\n")
		for _, bStmt := range s.Statements {
			writeStatement(sb, bStmt, level+1)
		}
		sb.WriteString(ind + "}\n")
	case *ast.GeneralForStatement:
		sb.WriteString(ind + "for (" + s.ItemVar.Type.String() + " " + s.ItemVar.Name + " : " + writeExpr(s.Collection) + ") {\n")
		for _, bStmt := range s.Statements {
			writeStatement(sb, bStmt, level+1)
		}
		sb.WriteString(ind + "}\n")
	case *ast.TryCatchStatement:
		sb.WriteString(ind + "try ")
		if len(s.Resources) > 0 {
			sb.WriteString("(")
			for i, r := range s.Resources {
				if i > 0 {
					sb.WriteString("; ")
				}
				sb.WriteString(r.Variable.Type.String() + " " + r.Variable.Name + " = " + writeExpr(r.InitExpr))
			}
			sb.WriteString(") ")
		}
		sb.WriteString("{\n")
		for _, tStmt := range s.TryBody {
			writeStatement(sb, tStmt, level+1)
		}
		for _, cb := range s.CatchBlocks {
			exNames := make([]string, len(cb.Exceptions))
			for i, ex := range cb.Exceptions {
				exNames[i] = ex.Name
			}
			fmt.Fprintf(sb, "%s} catch (%s %s) {\n", ind, strings.Join(exNames, " | "), cb.VarName)
			for _, cStmt := range cb.Body {
				writeStatement(sb, cStmt, level+1)
			}
		}
		if len(s.FinallyBody) > 0 {
			sb.WriteString(ind + "} finally {\n")
			for _, fStmt := range s.FinallyBody {
				writeStatement(sb, fStmt, level+1)
			}
		}
		sb.WriteString(ind + "}\n")
	case *ast.SynchronizedStatement:
		sb.WriteString(ind + "synchronized (" + writeExpr(s.LockExpr) + ") {\n")
		for _, bStmt := range s.Statements {
			writeStatement(sb, bStmt, level+1)
		}
		sb.WriteString(ind + "}\n")
	case *ast.BlockStatement:
		sb.WriteString(ind + "{\n")
		for _, bStmt := range s.Statements {
			writeStatement(sb, bStmt, level+1)
		}
		sb.WriteString(ind + "}\n")
	}
}

func writeExpr(expr ast.Expr) string {
	if expr == nil {
		return ""
	}
	switch e := expr.(type) {
	case *ast.ValueExpr:
		if e.IsString {
			return fmt.Sprintf("%q", e.Literal)
		}
		return e.Literal
	case *ast.VariableExpr:
		if e.Variable != nil {
			return lexicon.EscapeKeyword(e.Variable.Name)
		}
		return ""
	case *ast.MethodInvocationExpr:
		var sb strings.Builder
		if e.TargetExpr != nil {
			sb.WriteString(writeExpr(e.TargetExpr) + ".")
		} else if e.TargetType != nil {
			sb.WriteString(e.TargetType.String() + ".")
		}
		if len(e.Generics) > 0 {
			sb.WriteString("<")
			for i, g := range e.Generics {
				if i > 0 {
					sb.WriteString(", ")
				}
				sb.WriteString(g.String())
			}
			sb.WriteString(">")
		}
		sb.WriteString(e.MethodName + "(")
		for i, arg := range e.Arguments {
			if i > 0 {
				sb.WriteString(", ")
			}
			sb.WriteString(writeExpr(arg))
		}
		sb.WriteString(")")
		return sb.String()
	case *ast.NewObjectExpr:
		var sb strings.Builder
		sb.WriteString("new " + e.Type.String() + "(")
		for i, arg := range e.Arguments {
			if i > 0 {
				sb.WriteString(", ")
			}
			sb.WriteString(writeExpr(arg))
		}
		sb.WriteString(")")
		return sb.String()
	case *ast.AssignmentExpr:
		return writeExpr(e.Variable) + " = " + writeExpr(e.Value)
	case *ast.AssignmentOperationExpr:
		return writeExpr(e.Left) + " " + e.Operator + " " + writeExpr(e.Right)
	case *ast.BinaryOperationExpr:
		return writeExpr(e.Left) + " " + e.Operator + " " + writeExpr(e.Right)
	case *ast.UnaryOperationExpr:
		if e.Postfix {
			return writeExpr(e.Expr) + e.Operator
		}
		return e.Operator + writeExpr(e.Expr)
	case *ast.TernaryExpr:
		return writeExpr(e.Condition) + " ? " + writeExpr(e.ThenExpr) + " : " + writeExpr(e.ElseExpr)
	case *ast.CastExpr:
		return "(" + e.Type.String() + ") " + writeExpr(e.Expr)
	case *ast.InstanceofExpr:
		return writeExpr(e.Expr) + " instanceof " + e.CheckType.String()
	case *ast.EnumRefExpr:
		return e.Type.String() + "." + e.Value
	case *ast.ReferenceConstructorExpr:
		return e.Type.String() + "::" + e.MethodName
	case *ast.ArrayExpr:
		if e.Size != nil {
			return "new " + e.Type.Name + "[" + writeExpr(e.Size) + "]"
		}
		elems := make([]string, len(e.Elements))
		for i, el := range e.Elements {
			elems[i] = writeExpr(el)
		}
		return "new " + e.Type.Name + "[]{" + strings.Join(elems, ", ") + "}"
	case *ast.LambdaExpr:
		args := make([]string, len(e.Arguments))
		for i, a := range e.Arguments {
			args[i] = a.Name
		}
		argStr := "(" + strings.Join(args, ", ") + ")"
		if len(args) == 1 {
			argStr = args[0]
		}
		if e.BodyExpr != nil {
			return argStr + " -> " + writeExpr(e.BodyExpr)
		}
		return argStr + " -> { ... }"
	default:
		return ""
	}
}
