# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: Setup Librarian
description: Set up Go with build caching, install protoc and Go tools.
inputs:
  include_pnpm:
    description: 'Whether to include Node.js and pnpm setup'
    default: 'false'
  include_python:
    description: 'Whether to include Python setup'
    default: 'false'
runs:
  using: composite
  steps:
    - uses: actions/setup-go@v6
      with:
        go-version-file: "go.mod"
        cache: false
    - uses: actions/cache@v5
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: setup-librarian-${{ runner.os }}-${{ hashFiles('go.sum', '.github/actions/setup-librarian/action.yaml') }}
        restore-keys: setup-librarian-${{ runner.os }}-
    - uses: ./.github/actions/install-protoc
    - name: Install Go tools
      run: |
        go install tool
        go install ./cmd/librarian
      shell: bash
    - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      if: ${{ inputs.include_pnpm == 'true' }}
      with:
        node-version: "22"
    - name: "Set up pnpm via corepack"
      if: ${{ inputs.include_pnpm == 'true' }}
      run: |
        corepack enable pnpm
        corepack prepare pnpm@7.32.2 --activate
      shell: bash
    - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6
      if: ${{ inputs.include_python == 'true' }}
      with:
        python-version: "3.14"
