// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package swift

import (
	"fmt"
	"slices"
	"strings"

	"github.com/googleapis/librarian/internal/sidekick/api"
	"github.com/iancoleman/strcase"
)

// protoMessageTypeName resolves the fully-qualified Swift type name generated by SwiftProtobuf
// for a given api.Message. It constructs the name by walking up the message parent hierarchy,
// formatting type names in PascalCase, prepending the proto package prefix, and qualifying
// the path with ModulePath if it is not empty.
func (c *codec) protoMessageTypeName(m *api.Message) string {
	var path []string
	curr := m
	for curr != nil {
		path = append(path, pascalCase(curr.Name))
		curr = curr.Parent
	}
	slices.Reverse(path)
	fullName := fmt.Sprintf("%s%s", ProtoPackagePrefix(m.Package), strings.Join(path, "."))
	if c.ModulePath != "" {
		return fmt.Sprintf("%s.%s", c.ModulePath, fullName)
	}
	return fullName
}

// protoEnumTypeName resolves the fully-qualified Swift type name generated by SwiftProtobuf
// for a given api.Enum. For top-level enums, it formats the package prefix and enum name.
// For nested enums, it resolves the parent message's proto type name and appends the PascalCase enum name.
func (c *codec) protoEnumTypeName(e *api.Enum) string {
	mangled := pascalCase(e.Name)
	if mangled == "Type_" {
		// Protobuf uses `TypeEnum` in this case.
		mangled = "TypeEnum"
	}
	if e.Parent == nil {
		fullName := fmt.Sprintf("%s%s", ProtoPackagePrefix(e.Package), mangled)
		if c.ModulePath != "" {
			return fmt.Sprintf("%s.%s", c.ModulePath, fullName)
		}
		return fullName
	}
	return fmt.Sprintf("%s.%s", c.protoMessageTypeName(e.Parent), mangled)
}

func (c *codec) messageFileName(m *api.Message) string {
	var path []string
	curr := m
	for curr != nil {
		path = append(path, pascalCase(curr.Name))
		curr = curr.Parent
	}
	slices.Reverse(path)
	return strings.Join(path, "+")
}

func (c *codec) enumFileName(e *api.Enum) string {
	if e.Parent == nil {
		return pascalCase(e.Name)
	}
	return c.messageFileName(e.Parent) + "+" + pascalCase(e.Name)
}

// protoFieldName converts a protobuf field name to its corresponding SwiftProtobuf property name.
func protoFieldName(s string) string {
	// SwiftProtobuf appends a "_p" suffix to fields that conflict with standard Swift library
	// protocols (e.g. CustomStringConvertible, CustomDebugStringConvertible, Hashable)
	// or the SwiftProtobuf.Message protocol properties to avoid compiler errors.
	switch s {
	case "self":
		return "self_p"
	case "description":
		return "description_p"
	case "debug_description", "debugDescription":
		return "debugDescription_p"
	case "hash_value", "hashValue":
		return "hashValue_p"
	case "is_initialized", "isInitialized":
		return "isInitialized_p"
	case "serialized_size", "serializedSize":
		return "serializedSize_p"
	case "unknown_fields", "unknownFields":
		return "unknownFields_p"
	}
	parts := strings.Split(s, "_")
	var result strings.Builder
	first := true
	for _, part := range parts {
		if part == "" {
			continue
		}
		if first {
			result.WriteString(strcase.ToLowerCamel(part))
			first = false
		} else {
			if strings.ToLower(part) == "id" {
				result.WriteString("ID")
			} else {
				result.WriteString(strcase.ToCamel(part))
			}
		}
	}
	return escapeKeyword(result.String())
}

// protoFieldNamePascal converts a protobuf field name to its corresponding
// SwiftProtobuf PascalCase name (used for hasField helpers).
func protoFieldNamePascal(s string) string {
	// SwiftProtobuf appends a "_p" suffix to fields that conflict with standard Swift library
	// protocols (e.g. CustomStringConvertible, CustomDebugStringConvertible, Hashable)
	// or the SwiftProtobuf.Message protocol properties to avoid compiler errors.
	// We retain the "_p" casing for the PascalCase property representations (e.g., hasDescription_p).
	switch s {
	case "self":
		return "Self_p"
	case "description":
		return "Description_p"
	case "debug_description", "debugDescription":
		return "DebugDescription_p"
	case "hash_value", "hashValue":
		return "HashValue_p"
	case "is_initialized", "isInitialized":
		return "IsInitialized_p"
	case "serialized_size", "serializedSize":
		return "SerializedSize_p"
	case "unknown_fields", "unknownFields":
		return "UnknownFields_p"
	}
	parts := strings.Split(s, "_")
	var result strings.Builder
	for _, part := range parts {
		if part == "" {
			continue
		}
		if strings.ToLower(part) == "id" {
			result.WriteString("ID")
		} else {
			result.WriteString(strcase.ToCamel(part))
		}
	}
	return result.String()
}
