// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package swift

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/googleapis/librarian/internal/config"
	"github.com/googleapis/librarian/internal/sidekick/api"
)

func TestGenerateLandingPage(t *testing.T) {
	basicConfig := swiftConfig(t, nil)
	perServiceConfig := swiftConfig(t, nil)
	perServiceConfig.PerServiceTraits = true

	for _, test := range []struct {
		cfg            *config.SwiftPackage
		wantClientLink string
	}{
		{basicConfig, "- ``ServiceClient``\n"},
		{perServiceConfig, "- ``ServiceClient``: enabled by the `Service` feature.\n"},
	} {
		outDir := t.TempDir()
		inputType := api.NewTestMessage("Request").
			WithFields(api.NewTestField("key").WithType(api.TypezString))
		outputType := api.NewTestMessage("Response").
			WithFields(api.NewTestField("value").WithType(api.TypezString))
		method := api.NewTestMethod("Get").
			WithInput(inputType).
			WithOutput(outputType).
			WithVerb("GET").WithPathTemplate(&api.PathTemplate{})
		service := api.NewTestService("Service").WithMethods(method)
		model := api.NewTestAPI([]*api.Message{inputType, outputType}, nil, []*api.Service{service})
		model.PackageName = "test"
		model.Title = "Test Only API"
		model.Description = "The test API description\n--end description--\n"

		library := &config.Library{Swift: test.cfg}
		if err := Generate(t.Context(), model, outDir, library, nil); err != nil {
			t.Fatal(err)
		}
		landing := filepath.Join(outDir, "Sources", "Test", "Test.docc", "Test.md")
		contentBytes, err := os.ReadFile(landing)
		if err != nil {
			t.Fatal(err)
		}
		content := string(contentBytes)

		got := extractBlock(t, content, "- ``ServiceClient``", "\n")
		if diff := cmp.Diff(test.wantClientLink, got); diff != "" {
			t.Errorf("mismatch (-want +got):\n%s", diff)
		}

		// verify other output that does not depend on the configuration.
		got = extractBlock(t, content, "# ``Test``", "--end description--\n")
		want := `# ` + "``Test``" + `
<!-- Code generated by sidekick. DO NOT EDIT. -->

The test API description
--end description--
`
		if diff := cmp.Diff(want, got); diff != "" {
			t.Errorf("mismatch (-want +got):\n%s", diff)
		}
	}
}
