// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package rust_prost

import (
	"fmt"
	"strings"
	"time"

	"github.com/googleapis/librarian/internal/sidekick/parser"
)

type codec struct {
	GenerationYear string
	PackageName    string
	// If not empty, a segment of code to post-process the code generated by
	// Prost or Google-protobuf.
	PostProcessProtos []string
	// Most libraries are generated from `googleapis`. Rarely, we use protobuf,
	// gapic-showcase, or a different root.
	RootName string
	// ConvertIncludePackage is the proto package name (e.g., "google.cloud.secretmanager.v1")
	// whose include statement in `includes.rs` will be post-processed to append
	// `include!("../convert.rs");`. When set, prost_build creates an `includes.rs` file
	// and build.rs appends the convert module inclusion after the specified package's
	// include line. Used for generating conversion traits in hybrid crates.
	ConvertIncludePackage string
	// UnusedTypes is a list of proto type IDs that are not used in streaming RPCs.
	// They are configured with prost_build's extern_path to be mapped to a nonexistent
	// type so prost omits them from generation.
	UnusedTypes []string
}

func newCodec(cfg *parser.ModelConfig) *codec {
	year, _, _ := time.Now().Date()
	result := &codec{
		GenerationYear: fmt.Sprintf("%04d", year),
		PackageName:    "",
		RootName:       "googleapis",
	}
	for key, definition := range cfg.Codec {
		switch key {
		case "copyright-year":
			result.GenerationYear = definition
		case "package-name-override":
			result.PackageName = definition
		case "post-process-protos":
			result.PostProcessProtos = strings.Split(definition, "\n")
		case "root-name":
			result.RootName = definition
		case "convert-include-package":
			result.ConvertIncludePackage = definition
		case "unused-types":
			if definition != "" {
				result.UnusedTypes = strings.Split(definition, "\n")
			}
		default:
			// Ignore other options.
		}
	}
	return result
}
