// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package java

import (
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"testing"

	"github.com/google/go-cmp/cmp"
	"github.com/googleapis/librarian/internal/config"
)

func TestClean(t *testing.T) {
	t.Parallel()
	tmpDir := t.TempDir()

	libraryName := "google-cloud-secretmanager"
	version := "v1"
	// Create directories to clean
	dirs := []string{
		filepath.Join(tmpDir, libraryName, "src"),
		filepath.Join(tmpDir, fmt.Sprintf("proto-%s-%s", libraryName, version), "src"),
		filepath.Join(tmpDir, fmt.Sprintf("grpc-%s-%s", libraryName, version), "src"),
		filepath.Join(tmpDir, "samples", "snippets", "generated"),
		filepath.Join(tmpDir, "kept-dir"),
	}
	for _, dir := range dirs {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			t.Fatal(err)
		}
	}
	// Create files
	files := []string{
		filepath.Join(tmpDir, libraryName, "src", "Main.java"),
		filepath.Join(tmpDir, libraryName, "src", "main", "java", "com", "google", "cloud", "secretmanager", "v1", "stub", "Version.java"),
		filepath.Join(tmpDir, libraryName, "src", "main", "java", "com", "google", "cloud", "secretmanager", "v1", "Version.java"),
		filepath.Join(tmpDir, libraryName, "src", "test", "java", "com", "google", "cloud", "secretmanager", "v1", "it", "ITSecretManagerTest.java"),
		filepath.Join(tmpDir, fmt.Sprintf("proto-%s-%s", libraryName, version), "src", "manifest.txt"),
		filepath.Join(tmpDir, libraryName, "pom.xml"),
		filepath.Join(tmpDir, "kept-file.txt"),
		filepath.Join(tmpDir, "kept-dir", "file.txt"),
	}
	for _, file := range files {
		if err := os.MkdirAll(filepath.Dir(file), 0o755); err != nil {
			t.Fatal(err)
		}
		content := []byte("content")
		if filepath.Ext(file) == ".java" && !versionRegexp.MatchString(filepath.ToSlash(file)) && !itTestRegexp.MatchString(filepath.ToSlash(file)) {
			// Add marker to files we expect to be removed
			content = []byte("// AUTO-GENERATED DOCUMENTATION AND CLASS.\n" + string(content))
		}
		if err := os.WriteFile(file, content, 0o644); err != nil {
			t.Fatal(err)
		}
	}

	lib := &config.Library{
		Name:   "secretmanager",
		Output: tmpDir,
		Keep:   []string{"kept-file.txt", "kept-dir"},
		APIs: []*config.API{
			{
				Path: "google/cloud/secretmanager/v1",
				Java: &config.JavaAPI{},
			},
		},
		Java: &config.JavaModule{
			ArtifactID: "google-cloud-secretmanager",
			GroupID:    "com.google.cloud",
		},
	}
	if err := Clean(lib); err != nil {
		t.Fatal(err)
	}

	// Verify cleaned paths
	cleanedPaths := []string{
		filepath.Join(tmpDir, libraryName, "src", "Main.java"),
		filepath.Join(tmpDir, fmt.Sprintf("proto-%s-%s", libraryName, version), "src"),
		filepath.Join(tmpDir, fmt.Sprintf("grpc-%s-%s", libraryName, version), "src"),
		filepath.Join(tmpDir, fmt.Sprintf("proto-%s-%s", libraryName, version), "src", "manifest.txt"),
		filepath.Join(tmpDir, "samples", "snippets", "generated"),
		filepath.Join(tmpDir, libraryName, "src", "main", "java", "com", "google", "cloud", "secretmanager", "v1", "Version.java"),
	}
	for _, p := range cleanedPaths {
		if _, err := os.Stat(p); !errors.Is(err, fs.ErrNotExist) {
			t.Errorf("expected path %s to be removed, but it still exists", p)
		}
	}
	// Verify kept paths
	keptPaths := []string{
		filepath.Join(tmpDir, "kept-file.txt"),
		filepath.Join(tmpDir, "kept-dir", "file.txt"),
		filepath.Join(tmpDir, libraryName, "pom.xml"),
		filepath.Join(tmpDir, fmt.Sprintf("proto-%s-%s", libraryName, version)),
		filepath.Join(tmpDir, fmt.Sprintf("grpc-%s-%s", libraryName, version)),
		filepath.Join(tmpDir, libraryName, "src", "main", "java", "com", "google", "cloud", "secretmanager", "v1", "stub", "Version.java"),
		filepath.Join(tmpDir, libraryName, "src", "test", "java", "com", "google", "cloud", "secretmanager", "v1", "it", "ITSecretManagerTest.java"),
	}
	for _, p := range keptPaths {
		if _, err := os.Stat(p); err != nil {
			t.Errorf("expected path %s to be kept, but it was removed: %v", p, err)
		}
	}
}

func TestShouldCleanMarkerPath(t *testing.T) {
	for _, test := range []struct {
		name     string
		fileName string
		content  string
		want     bool
	}{
		{
			name:     "generated java file",
			fileName: "Generated.java",
			content:  "package com.foo;\nimport bar;\n" + autoGeneratedMarker + "\npublic class Generated {}",
			want:     true,
		},
		{
			name:     "manual java file",
			fileName: "Manual.java",
			content:  "package com.foo;\npublic class Manual {}",
			want:     false,
		},
		{
			name:     "annotation only java file",
			fileName: "AnnotationOnly.java",
			content:  "package com.foo;\n@Generated(\"by gapic-generator-java\")\npublic class AnnotationOnly {}",
			want:     true,
		},
		{
			name:     "gapic_metadata.json",
			fileName: "gapic_metadata.json",
			want:     true,
		},
		{
			name:     "reflect-config.json",
			fileName: "reflect-config.json",
			want:     true,
		},
		{
			name:     "non-java file",
			fileName: "Other.txt",
			content:  "just some text",
			want:     false,
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			tmpDir := t.TempDir()
			path := filepath.Join(tmpDir, test.fileName)
			if err := os.WriteFile(path, []byte(test.content), 0o644); err != nil {
				t.Fatal(err)
			}

			entries, err := os.ReadDir(tmpDir)
			if err != nil {
				t.Fatal(err)
			}
			if len(entries) != 1 {
				t.Fatalf("expected 1 entry, got %d", len(entries))
			}

			got, err := shouldCleanMarkerPath(path, entries[0])
			if err != nil {
				t.Fatal(err)
			}
			if got != test.want {
				t.Errorf("shouldCleanMarkerPath() = %v, want %v", got, test.want)
			}
		})
	}
}
func TestCleanPatterns(t *testing.T) {
	t.Parallel()
	for _, test := range []struct {
		name    string
		library *config.Library
		want    map[string]bool
	}{
		{
			name: "default_case",
			library: &config.Library{
				Name: "secretmanager",
				APIs: []*config.API{
					{
						Path: "google/cloud/secretmanager/v1",
						Java: &config.JavaAPI{},
					},
				},
				Java: &config.JavaModule{
					ArtifactID: "google-cloud-secretmanager",
					GroupID:    "com.google.cloud",
				},
			},
			want: map[string]bool{
				filepath.Join("google-cloud-secretmanager", "src"):          true,
				filepath.Join("proto-google-cloud-secretmanager-v1", "src"): false,
				filepath.Join("grpc-google-cloud-secretmanager-v1", "src"):  false,
				filepath.Join("samples", "snippets", "generated"):           false,
				".repo-metadata.json": false,
			},
		},
		{
			name: "with proto only path",
			library: &config.Library{
				Name: "accesscontextmanager",
				APIs: []*config.API{
					{
						Path: "google/identity/accesscontextmanager/v1",
						Java: &config.JavaAPI{},
					},
					{
						Path: "google/identity/accesscontextmanager/type",
						Java: &config.JavaAPI{
							GenerateGAPIC:         new(false),
							GenerateResourceNames: new(false),
						},
					},
				},
				Java: &config.JavaModule{
					ArtifactID: "google-cloud-accesscontextmanager",
					GroupID:    "com.google.cloud",
				},
			},
			want: map[string]bool{
				"google-cloud-accesscontextmanager/src":            true,
				"proto-google-cloud-accesscontextmanager-type/src": false,
				"proto-google-cloud-accesscontextmanager-v1/src":   false,
				"grpc-google-cloud-accesscontextmanager-v1/src":    false,
				"grpc-google-cloud-accesscontextmanager-type/src":  false,
				filepath.Join("samples", "snippets", "generated"):  false,
				".repo-metadata.json":                              false,
			},
		},
		{
			name: "with_overrides",
			library: &config.Library{
				Name: "secretmanager",
				Java: &config.JavaModule{
					ArtifactID: "secretmanager-special",
					GroupID:    "com.google.cloud",
				},
				APIs: []*config.API{
					{
						Path: "google/cloud/secretmanager/v1",
						Java: &config.JavaAPI{},
					},
				},
			},
			want: map[string]bool{
				filepath.Join("secretmanager-special", "src"):          true,
				filepath.Join("proto-secretmanager-special-v1", "src"): false,
				filepath.Join("grpc-secretmanager-special-v1", "src"):  false,
				filepath.Join("samples", "snippets", "generated"):      false,
				".repo-metadata.json":                                  false,
			},
		},
		{
			name: "multiple_apis",
			library: &config.Library{
				Name: "secretmanager",
				APIs: []*config.API{
					{
						Path: "google/cloud/secretmanager/v1",
						Java: &config.JavaAPI{},
					},
					{
						Path: "google/cloud/secretmanager/v1beta1",
						Java: &config.JavaAPI{},
					},
				},
				Java: &config.JavaModule{
					ArtifactID: "google-cloud-secretmanager",
					GroupID:    "com.google.cloud",
				},
			},
			want: map[string]bool{
				filepath.Join("google-cloud-secretmanager", "src"):               true,
				filepath.Join("proto-google-cloud-secretmanager-v1", "src"):      false,
				filepath.Join("grpc-google-cloud-secretmanager-v1", "src"):       false,
				filepath.Join("proto-google-cloud-secretmanager-v1beta1", "src"): false,
				filepath.Join("grpc-google-cloud-secretmanager-v1beta1", "src"):  false,
				filepath.Join("samples", "snippets", "generated"):                false,
				".repo-metadata.json": false,
			},
		},
		{
			name: "gapic_artifact_id_override",
			library: &config.Library{
				Name: "secretmanager",
				APIs: []*config.API{
					{
						Path: "google/cloud/secretmanager/v1",
						Java: &config.JavaAPI{
							GAPICArtifactIDOverride: "custom-gapic-artifact",
						},
					},
				},
				Java: &config.JavaModule{
					ArtifactID: "google-cloud-secretmanager",
					GroupID:    "com.google.cloud",
				},
			},
			want: map[string]bool{
				filepath.Join("custom-gapic-artifact", "src"):          true,
				filepath.Join("proto-custom-gapic-artifact-v1", "src"): false,
				filepath.Join("grpc-custom-gapic-artifact-v1", "src"):  false,
				filepath.Join("samples", "snippets", "generated"):      false,
				".repo-metadata.json":                                  false,
			},
		},
		{
			name: "gapic_disabled_for_all_apis",
			library: &config.Library{
				Name: "secretmanager",
				APIs: []*config.API{
					{
						Path: "google/cloud/secretmanager/v1",
						Java: &config.JavaAPI{
							GenerateGAPIC: new(false),
						},
					},
				},
				Java: &config.JavaModule{
					ArtifactID: "google-cloud-secretmanager",
					GroupID:    "com.google.cloud",
				},
			},
			want: map[string]bool{
				filepath.Join("proto-google-cloud-secretmanager-v1", "src"): false,
				filepath.Join("grpc-google-cloud-secretmanager-v1", "src"):  false,
				filepath.Join("samples", "snippets", "generated"):           false,
				".repo-metadata.json": false,
			},
		},
		{
			name: "proto_and_grpc_disabled",
			library: &config.Library{
				Name: "secretmanager",
				APIs: []*config.API{
					{
						Path: "google/cloud/secretmanager/v1",
						Java: &config.JavaAPI{
							GenerateProto: new(false),
							GenerateGRPC:  new(false),
						},
					},
				},
				Java: &config.JavaModule{
					ArtifactID: "google-cloud-secretmanager",
					GroupID:    "com.google.cloud",
				},
			},
			want: map[string]bool{
				filepath.Join("google-cloud-secretmanager", "src"): true,
				filepath.Join("samples", "snippets", "generated"):  false,
				".repo-metadata.json":                              false,
			},
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			got := cleanPatterns(test.library)
			if diff := cmp.Diff(test.want, got); diff != "" {
				t.Errorf("mismatch (-want +got):\n%s", diff)
			}
		})
	}
}

func TestShouldPreserve(t *testing.T) {
	keepSet := map[string]bool{
		"explicitly/kept.txt": true,
	}
	for _, test := range []struct {
		name string
		path string
		want bool
	}{
		{
			name: "explicitly kept",
			path: "explicitly/kept.txt",
			want: true,
		},
		{
			name: "cloud version stub",
			path: "src/main/java/com/google/cloud/secretmanager/v1/stub/Version.java",
			want: true,
		},
		{
			name: "non-cloud version stub",
			path: "src/main/java/com/google/devicesandservices/health/v4/stub/Version.java",
			want: true,
		},
		{
			name: "other java file",
			path: "src/main/java/com/google/cloud/secretmanager/v1/Other.java",
			want: false,
		},
	} {
		t.Run(test.name, func(t *testing.T) {
			if got := shouldPreserve(test.path, keepSet); got != test.want {
				t.Errorf("shouldPreserve(%q) = %v, want %v", test.path, got, test.want)
			}
		})
	}
}

func TestHasMarker_BoundaryAndEdgeCases(t *testing.T) {
	t.Parallel()

	t.Run("empty file", func(t *testing.T) {
		t.Parallel()
		tmp := filepath.Join(t.TempDir(), "Empty.java")
		if err := os.WriteFile(tmp, []byte{}, 0o644); err != nil {
			t.Fatal(err)
		}
		got, err := hasMarker(tmp)
		if err != nil {
			t.Fatal(err)
		}
		if got {
			t.Errorf("hasMarker(empty) = true, want false")
		}
	})

	t.Run("short file without marker", func(t *testing.T) {
		t.Parallel()
		tmp := filepath.Join(t.TempDir(), "Short.java")
		if err := os.WriteFile(tmp, []byte("short content"), 0o644); err != nil {
			t.Fatal(err)
		}
		got, err := hasMarker(tmp)
		if err != nil {
			t.Fatal(err)
		}
		if got {
			t.Errorf("hasMarker(short) = true, want false")
		}
	})

	t.Run("large file without marker", func(t *testing.T) {
		t.Parallel()
		tmp := filepath.Join(t.TempDir(), "LargeNoMarker.java")
		data := make([]byte, 50000)
		for i := range data {
			data[i] = 'A'
		}
		if err := os.WriteFile(tmp, data, 0o644); err != nil {
			t.Fatal(err)
		}
		got, err := hasMarker(tmp)
		if err != nil {
			t.Fatal(err)
		}
		if got {
			t.Errorf("hasMarker(large without marker) = true, want false")
		}
	})

	t.Run("large file with marker at end", func(t *testing.T) {
		t.Parallel()
		tmp := filepath.Join(t.TempDir(), "LargeWithMarkerEnd.java")
		data := make([]byte, 50000)
		for i := range data {
			data[i] = 'A'
		}
		data = append(data, []byte(autoGeneratedMarker)...)
		if err := os.WriteFile(tmp, data, 0o644); err != nil {
			t.Fatal(err)
		}
		got, err := hasMarker(tmp)
		if err != nil {
			t.Fatal(err)
		}
		if !got {
			t.Errorf("hasMarker(large with marker at end) = false, want true")
		}
	})

	t.Run("marker split across 8192 buffer boundary", func(t *testing.T) {
		t.Parallel()
		marker := []byte(autoGeneratedMarker)
		markerLen := len(marker)

		// Test split at every possible offset spanning across index 8192
		for splitOffset := 1; splitOffset < markerLen; splitOffset++ {
			tmp := filepath.Join(t.TempDir(), fmt.Sprintf("Split_%d.java", splitOffset))
			data := make([]byte, 8192-splitOffset)
			for i := range data {
				data[i] = 'x'
			}
			data = append(data, marker...)
			// Append some trailing data after the marker
			data = append(data, []byte("\n// trailing comments\n")...)

			if err := os.WriteFile(tmp, data, 0o644); err != nil {
				t.Fatal(err)
			}
			got, err := hasMarker(tmp)
			if err != nil {
				t.Fatalf("splitOffset %d: hasMarker returned error: %v", splitOffset, err)
			}
			if !got {
				t.Errorf("splitOffset %d: hasMarker = false, want true", splitOffset)
			}
		}
	})

	t.Run("annotation split across 8192 buffer boundary", func(t *testing.T) {
		t.Parallel()
		marker := []byte(autoGeneratedAnnotation)
		markerLen := len(marker)

		for splitOffset := 1; splitOffset < markerLen; splitOffset++ {
			tmp := filepath.Join(t.TempDir(), fmt.Sprintf("SplitAnnot_%d.java", splitOffset))
			data := make([]byte, 8192-splitOffset)
			for i := range data {
				data[i] = 'y'
			}
			data = append(data, marker...)
			data = append(data, []byte("\n// trailing comments\n")...)

			if err := os.WriteFile(tmp, data, 0o644); err != nil {
				t.Fatal(err)
			}
			got, err := hasMarker(tmp)
			if err != nil {
				t.Fatalf("splitOffset %d: hasMarker returned error: %v", splitOffset, err)
			}
			if !got {
				t.Errorf("splitOffset %d: hasMarker = false, want true", splitOffset)
			}
		}
	})

	t.Run("file not found error", func(t *testing.T) {
		t.Parallel()
		got, err := hasMarker(filepath.Join(t.TempDir(), "nonexistent.java"))
		if err == nil {
			t.Errorf("hasMarker(nonexistent) expected error, got nil")
		}
		if got {
			t.Errorf("hasMarker(nonexistent) = true, want false")
		}
	})
}
