// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package protowriter serializes Java source code and configuration into CodeGeneratorResponse.
package protowriter

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/googleapis/librarian/internal/gapic/java/engine/writer"
	"github.com/googleapis/librarian/internal/gapic/java/model"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/pluginpb"
)

// Write builds the pluginpb.CodeGeneratorResponse from composed classes and configs.
func Write(ctx *model.GapicContext, classes []*model.GapicClass, pkgInfo *model.GapicPackageInfo, reflectConfigs []*model.ReflectConfig) *pluginpb.CodeGeneratorResponse {
	resp := &pluginpb.CodeGeneratorResponse{
		SupportedFeatures: proto.Uint64(uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)),
	}

	for _, c := range classes {
		if c == nil || c.ClassDefinition == nil {
			continue
		}
		content := writer.WriteClass(c.ClassDefinition)
		filePath := packageToPath(c.ClassDefinition.PackageName, c.ClassDefinition.Name+".java")
		resp.File = append(resp.File, &pluginpb.CodeGeneratorResponse_File{
			Name:    new(filePath),
			Content: new(content),
		})
	}

	if pkgInfo != nil && pkgInfo.PackageName != "" {
		pkgContent := writePackageInfo(pkgInfo)
		pkgPath := packageToPath(pkgInfo.PackageName, "package-info.java")
		resp.File = append(resp.File, &pluginpb.CodeGeneratorResponse_File{
			Name:    new(pkgPath),
			Content: new(pkgContent),
		})
	}

	if ctx.HasMetadata {
		// reflect-config.json
		if len(reflectConfigs) > 0 {
			rawJSON, err := json.MarshalIndent(reflectConfigs, "", "  ")
			if err == nil {
				reflectPath := fmt.Sprintf("META-INF/native-image/%s/reflect-config.json", ctx.Services[0].PackageName)
				resp.File = append(resp.File, &pluginpb.CodeGeneratorResponse_File{
					Name:    new(reflectPath),
					Content: new(string(rawJSON) + "\n"),
				})
			}
		}

		// gapic_metadata.json
		metadataJSON := generateGapicMetadataJSON(ctx)
		resp.File = append(resp.File, &pluginpb.CodeGeneratorResponse_File{
			Name:    new("gapic_metadata.json"),
			Content: new(metadataJSON),
		})
	}

	return resp
}

func packageToPath(pkgName, fileName string) string {
	if pkgName == "" {
		return fileName
	}
	dir := strings.ReplaceAll(pkgName, ".", "/")
	return dir + "/" + fileName
}

func writePackageInfo(info *model.GapicPackageInfo) string {
	var sb strings.Builder
	sb.WriteString("// Generated by gapic-generator-java. DO NOT EDIT!\n\n")
	sb.WriteString("/**\n")
	fmt.Fprintf(&sb, " * %s\n", info.Description)
	sb.WriteString(" */\n")
	for _, ann := range info.Annotations {
		if ann != nil && ann.Type != nil {
			fmt.Fprintf(&sb, "@%s\n", ann.Type.Name)
		}
	}
	fmt.Fprintf(&sb, "package %s;\n", info.PackageName)
	return sb.String()
}

func generateGapicMetadataJSON(ctx *model.GapicContext) string {
	type clientMethod struct {
		Methods []string `json:"methods"`
	}
	type serviceMeta struct {
		LibraryClient string                  `json:"libraryClient"`
		Rpcs          map[string]clientMethod `json:"rpcs"`
	}
	type schemaMeta struct {
		Schema   string                 `json:"schema"`
		Comment  string                 `json:"comment"`
		Language string                 `json:"language"`
		ProtoPkg string                 `json:"protoPackage"`
		Library  string                 `json:"libraryPackage"`
		Services map[string]serviceMeta `json:"services"`
	}

	meta := schemaMeta{
		Schema:   "1.0",
		Comment:  "This file maps proto services/RPCs to the corresponding library clients/methods.",
		Language: "java",
		Services: make(map[string]serviceMeta),
	}

	if len(ctx.Services) > 0 {
		meta.ProtoPkg = ctx.Services[0].OriginalJavaPackage
		meta.Library = ctx.Services[0].PackageName
	}

	for _, svc := range ctx.Services {
		sMeta := serviceMeta{
			LibraryClient: svc.Name + "Client",
			Rpcs:          make(map[string]clientMethod),
		}
		for _, m := range svc.Methods {
			sMeta.Rpcs[m.Name] = clientMethod{
				Methods: []string{strings.ToLower(m.Name[:1]) + m.Name[1:]},
			}
		}
		meta.Services[svc.Name] = sMeta
	}

	b, _ := json.MarshalIndent(meta, "", "  ")
	return string(b) + "\n"
}
