# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
name: Python
on: [push, pull_request, merge_group]
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-24.04
    # Presubmit jobs must complete within 5 minutes. See CONTRIBUTING.md.
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - uses: ./.github/actions/setup-librarian
        with:
          include_python: 'true'
      - name: Install pandoc
        run: |
          set -e
          curl -fsSL --retry 5 --retry-delay 15 -o /tmp/pandoc.tar.gz https://github.com/jgm/pandoc/releases/download/$VERSION/pandoc-$VERSION-linux-amd64.tar.gz
          sudo tar -xvf /tmp/pandoc.tar.gz -C /usr/local --strip-components=1
          pandoc --version
        env:
          VERSION: 3.8.2
      - name: "Checkout google-cloud-python (sparse)"
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          repository: googleapis/google-cloud-python
          path: google-cloud-python
          depth: 1
          sparse-checkout: |
            librarian.yaml
          sparse-checkout-cone-mode: false
          persist-credentials: false
      - name: Install Python dependencies
        run: librarian -v install python
        working-directory: google-cloud-python
      - name: Run tests
        run: go run ./tool/cmd/coverage ./internal/librarian/python
